[workspace]
resolver = "3"
default-members = ["apps/x-chaos"]
members = [
    "apps/x-chaos",
    "crates/*",
]

[workspace.package]
version = "0.1.0"
authors = ["Nguyễn Quý Ngọc"]
edition = "2024"
rust-version = "1.97.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ChaoswareHQ/x-chaos"
homepage = "https://github.com/ChaoswareHQ/x-chaos"
documentation = "https://chaoswarehq.github.io/x-chaos/"
readme = "README.md"

[workspace.dependencies]
# Workspace crates
audio       = { path = "crates/audio" }
base        = { path = "crates/base" }
controller  = { path = "crates/controller" }
gfx         = { path = "crates/gfx" }
network     = { path = "crates/network" }
emulators   = { path = "crates/emulators" }

# Published x-* crates
x-gfx        = "0.1.0"
x-audio      = "0.1.0"
x-controller = "0.1.0"
x-nes        = "0.1.1"

# GUI
slint = "1.17.1"
anyhow = "1.0.103"
