[package]
name = "controller"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[features]
default = ["std"]
std = ["dep:x-controller"]
mcu = []

[lib]
name = "controller"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
base = { workspace = true }
x-controller = { workspace = true, optional = true }
