[package]
name = "x-chaos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[[bin]]
name = "x-chaos"
path = "src/main.rs"

[features]
default = ["desktop"]
desktop = [
    "slint/backend-winit",
    "gfx/gpu",
    "audio/std",
    "controller/std",
]
mcu = [
    "gfx/mcu",
    "audio/mcu",
    "controller/mcu",
]

[dependencies]
anyhow.workspace = true
base.workspace = true
emulators.workspace = true
gfx.workspace = true
audio.workspace = true
controller.workspace = true
network.workspace = true
slint.workspace = true

[build-dependencies]
slint-build = "1"
