[package]
name = "base"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[features]
default = ["std"]
std = []
mcu = []

[lib]
name = "base"
crate-type = ["lib", "cdylib", "staticlib"]

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
