[package]
name = "gfx"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[features]
default = ["gpu"]
gpu = ["dep:x-gfx"]
mcu = []

[lib]
name = "gfx"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
base = { workspace = true }
x-gfx = { workspace = true, optional = true }
