[package]
name = "gfx"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true

[features]
default = ["gpu"]
gpu = ["dep:winit", "dep:softbuffer"]
mcu = []

[lib]
name = "gfx"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
base = { workspace = true }
winit = { version = "0.30.13", optional = true, default-features = false, features = [
    "rwh_06", "x11", "wayland", "wayland-dlopen",
] }
softbuffer = { version = "0.4.8", optional = true }
